### ISSUE TITLE
suggest Datenstand etc. as comments in .csv s

### ISSUE THREAD

**Issue by denis-bz** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#9]
Not an issue, just a suggestion:

it's useful to put # comment lines at the top of .csv s, so users can later see what's there. For example

    # Datenstand: ... (updated ...)
    # from https://github.com/robert-koch-institut/...
    # COVID patients hospitalised over 7 days, per Bundesland and age group
    # see also ...
    # License ...
    ...

Every .csv reader can be told to skip # comments, e.g. `pandas.read_csv( ... comment="#" )`
(github complains, but downloads ok).
Another way of doing this would be a `file.csvinfo` parallel to each `file.csv`;
the advantage of comments is that they stay with downloaded .csv s.
What do you think ?

**Comment by HannesWuensche** [comment]
Dear @denis-bz,

thank you for that suggestion. 
We provide basic metadata in our .zenodo.json. So I'd say an extra .csvinfo file would simply double the information with no further gain. 
Since other Issues have suggested that we get rid of our archive folders, adding a comment to the data.csv files could be an solution to secure that the "Datenstand" stays attached to the files. We will discuss it in our next team meeting along with the archive issues. 

Best Regards
@HannesWuensche 
Team RKI | Open Data
